// CampusIdleGoodsTrading/frontend/src/pages/ProductList.jsx
import React, { useState, useEffect } from 'react'
import { Row, Col, Card, Tag, Button, Typography, Space, Select, Input, Pagination, Empty } from 'antd'
import { ShoppingCartOutlined, HeartOutlined, SearchOutlined } from '@ant-design/icons'
import { useNavigate, useSearchParams } from 'react-router-dom'
import AppLayout from '../components/Layout'
import { publicApi, userApi } from '../utils/api'
import { useUserStore } from '../store/useStore'

const { Title } = Typography

function ProductList() {
  const navigate = useNavigate()
  const [searchParams, setSearchParams] = useSearchParams()
  const { user, setCartCount } = useUserStore()
  
  const [products, setProducts] = useState([])
  const [categories, setCategories] = useState([])
  const [loading, setLoading] = useState(false)
  const [pagination, setPagination] = useState({ current: 1, pageSize: 20, total: 0 })
  const [filters, setFilters] = useState({
    keyword: searchParams.get('keyword') || '',
    category_id: searchParams.get('category_id') || '',
    sort: ''
  })

  useEffect(() => {
    loadCategories()
  }, [])

  useEffect(() => {
    loadProducts()
  }, [filters, pagination.current, pagination.pageSize])

  const loadCategories = async () => {
    try {
      const res = await publicApi.getCategories()
      setCategories(res.data)
    } catch (error) {
      console.error(error)
    }
  }

  const loadProducts = async () => {
    setLoading(true)
    try {
      const params = {
        page: pagination.current,
        page_size: pagination.pageSize,
        ...(filters.keyword && { keyword: filters.keyword }),
        ...(filters.category_id && { category_id: filters.category_id })
      }
      const res = await publicApi.getProducts(params)
      setProducts(res.data.list)
      setPagination(p => ({ ...p, total: res.data.total }))
    } catch (error) {
      console.error(error)
    } finally {
      setLoading(false)
    }
  }

  const handleAddToCart = async (e, product) => {
    e.stopPropagation()
    if (!user) {
      navigate('/login')
      return
    }
    try {
      await userApi.addToCart({ product_id: product.id, quantity: 1 })
      const res = await userApi.getCartCount()
      setCartCount(res.data.count)
    } catch (error) {
      console.error(error)
    }
  }

  const ProductCard = ({ product }) => (
    <Card
      hoverable
      className="product-card"
      cover={
        <img 
          alt={product.name} 
          src={product.image || 'https://picsum.photos/400/200'} 
          onClick={() => navigate(`/products/${product.id}`)}
        />
      }
      actions={[
        <Button 
          type="text" 
          icon={<ShoppingCartOutlined />}
          onClick={(e) => handleAddToCart(e, product)}
        >
          加入购物车
        </Button>,
        <Button type="text" icon={<HeartOutlined />} onClick={(e) => {
          e.stopPropagation()
          if (!user) {
            navigate('/login')
            return
          }
          userApi.toggleFavorite(product.id)
        }}>收藏</Button>
      ]}
    >
      <Card.Meta
        title={<div onClick={() => navigate(`/products/${product.id}`)} style={{ cursor: 'pointer' }}>
          {product.name.length > 30 ? product.name.substring(0, 30) + '...' : product.name}
        </div>}
        description={
          <Space direction="vertical" size="small" style={{ width: '100%' }}>
            <div>
              <span className="product-price">¥{product.price}</span>
              {product.originalPrice > product.price && (
                <span className="product-original-price">¥{product.originalPrice}</span>
              )}
            </div>
            <Space size={8}>
              {product.category && <Tag color="blue">{product.category.name}</Tag>}
              <Tag color="green">库存: {product.stock}</Tag>
            </Space>
          </Space>
        }
      />
    </Card>
  )

  return (
    <AppLayout>
      <div style={{ marginBottom: 24 }}>
        <Title level={3}>商品列表</Title>
        
        <Card style={{ marginBottom: 16 }}>
          <Space direction="vertical" size="middle" style={{ width: '100%' }}>
            <Space>
              <span style={{ width: 60 }}>分类:</span>
              <Select
                style={{ width: 200 }}
                value={filters.category_id || undefined}
                placeholder="全部分类"
                allowClear
                onChange={(value) => setFilters(f => ({ ...f, category_id: value || '' }))}
              >
                <Select.Option value="">全部分类</Select.Option>
                {categories.map(cat => (
                  <Select.Option key={cat.id} value={cat.id}>{cat.name}</Select.Option>
                ))}
              </Select>
            </Space>
            <Space>
              <span style={{ width: 60 }}>搜索:</span>
              <Input.Search
                placeholder="搜索商品名称..."
                allowClear
                enterButton={<SearchOutlined />}
                value={filters.keyword}
                onSearch={(value) => setFilters(f => ({ ...f, keyword: value }))}
                style={{ width: 400 }}
              />
            </Space>
          </Space>
        </Card>

        {products.length > 0 ? (
          <>
            <Row gutter={[16, 16]}>
              {products.map(product => (
                <Col xs={12} sm={8} md={6} lg={6} key={product.id}>
                  <ProductCard product={product} />
                </Col>
              ))}
            </Row>
            <div style={{ textAlign: 'center', marginTop: 24 }}>
              <Pagination
                current={pagination.current}
                pageSize={pagination.pageSize}
                total={pagination.total}
                showSizeChanger
                pageSizeOptions={['12', '20', '40']}
                showTotal={(total) => `共 ${total} 件商品`}
                onChange={(page, pageSize) => setPagination(p => ({ ...p, current: page, pageSize }))}
              />
            </div>
          </>
        ) : (
          <Empty description="暂无商品" />
        )}
      </div>
    </AppLayout>
  )
}

export default ProductList

// PriceComparisonMonitoring/frontend/src/views/ProductList.vue
<template>
  <div>
    <div class="page-header">
      <h2>监控列表</h2>
      <div>
        <el-button type="primary" @click="$router.push('/products/add')">
          <el-icon><Plus /></el-icon>
          添加商品
        </el-button>
      </div>
    </div>
    
    <el-row :gutter="20">
      <el-col :span="4">
        <div class="card-container" style="padding: 12px;">
          <div class="group-item active" @click="currentGroup = null">
            <span class="group-icon">📦</span>
            <span class="group-name">全部商品</span>
            <span class="group-count">{{ totalCount }}</span>
          </div>
          
          <div
            v-for="group in groups"
            :key="group.id"
            class="group-item"
            :class="{ active: currentGroup === group.id }"
            @click="currentGroup = group.id"
          >
            <span class="group-icon">{{ group.icon || '📁' }}</span>
            <span class="group-name">{{ group.name }}</span>
            <span class="group-count">{{ group.product_count }}</span>
          </div>
          
          <el-divider style="margin: 12px 0;" />
          
          <div
            class="group-item"
            :class="{ active: filterFavorite }"
            @click="filterFavorite = !filterFavorite"
          >
            <span class="group-icon">⭐</span>
            <span class="group-name">我的收藏</span>
          </div>
        </div>
      </el-col>
      
      <el-col :span="20">
        <div class="card-container">
          <div class="search-bar">
            <el-input
              v-model="keyword"
              placeholder="搜索商品名称"
              clearable
              style="width: 300px;"
              @keyup.enter="loadProducts"
            >
              <template #prefix>
                <el-icon><Search /></el-icon>
              </template>
            </el-input>
            
            <el-select v-model="statusFilter" placeholder="状态" style="width: 120px;" @change="loadProducts">
              <el-option label="全部" value="" />
              <el-option label="监控中" value="1" />
              <el-option label="已停止" value="0" />
            </el-select>
            
            <el-button type="primary" @click="loadProducts">
              <el-icon><Search /></el-icon>
              搜索
            </el-button>
          </div>
          
          <div v-if="products.length === 0" class="empty-state">
            <el-icon class="empty-icon"><ShoppingCart /></el-icon>
            <p class="empty-text">暂无商品</p>
            <el-button type="primary" style="margin-top: 16px;" @click="$router.push('/products/add')">
              添加第一个商品
            </el-button>
          </div>
          
          <el-row v-else :gutter="16">
            <el-col v-for="product in products" :key="product.id" :span="6">
              <div class="product-card" @click="$router.push(`/products/${product.id}`)">
                <img
                  v-if="product.image_url"
                  :src="product.image_url"
                  class="product-image"
                  alt=""
                />
                <div v-else class="product-image" style="display: flex; align-items: center; justify-content: center;">
                  <el-icon :size="48"><ShoppingBag /></el-icon>
                </div>
                
                <h3 class="product-title" :title="product.title">{{ product.title }}</h3>
                
                <div class="product-price">
                  <span class="currency">¥</span>
                  {{ product.current_price?.toFixed(2) || '--' }}
                </div>
                
                <div v-if="product.original_price" class="product-original-price">
                  ¥{{ product.original_price.toFixed(2) }}
                </div>
                
                <div class="product-meta">
                  <span
                    v-if="product.lowest_price && product.current_price <= product.lowest_price"
                    class="price-change down"
                  >
                    历史最低
                  </span>
                  <span
                    v-else-if="product.highest_price && product.current_price >= product.highest_price"
                    class="price-change up"
                  >
                    历史最高
                  </span>
                  
                  <div>
                    <el-icon
                      style="cursor: pointer; color: #e6a23c;"
                      @click.stop="toggleFavorite(product)"
                    >
                      <component :is="product.is_favorite ? 'StarFilled' : 'Star'" />
                    </el-icon>
                  </div>
                </div>
              </div>
            </el-col>
          </div>
          
          <div v-if="total > pageSize" style="text-align: center; margin-top: 20px;">
            <el-pagination
              v-model:current-page="page"
              :page-size="pageSize"
              :total="total"
              layout="prev, pager, next"
              @current-change="loadProducts"
            />
          </div>
        </div>
      </el-col>
    </el-row>
  </div>
</template>

<script setup>
import { ref, onMounted } from 'vue'
import { productApi, groupApi } from '@/api'
import { ElMessage } from 'element-plus'

const products = ref([])
const groups = ref([])
const currentGroup = ref(null)
const filterFavorite = ref(false)
const keyword = ref('')
const statusFilter = ref('')
const page = ref(1)
const pageSize = ref(12)
const total = ref(0)
const totalCount = ref(0)

onMounted(() => {
  loadGroups()
  loadProducts()
})

const loadGroups = async () => {
  try {
    const res = await groupApi.getList()
    groups.value = res.data || []
    totalCount.value = groups.value.reduce((sum, g) => sum + (g.product_count || 0), 0)
  } catch (e) {
    console.error(e)
  }
}

const loadProducts = async () => {
  try {
    const params = {
      page: page.value,
      page_size: pageSize.value
    }
    
    if (currentGroup.value) {
      params.group_id = currentGroup.value
    }
    if (filterFavorite.value) {
      params.is_favorite = 1
    }
    if (keyword.value) {
      params.keyword = keyword.value
    }
    if (statusFilter.value) {
      params.status = statusFilter.value
    }
    
    const res = await productApi.getList(params)
    products.value = res.data?.list || []
    total.value = res.data?.total || 0
  } catch (e) {
    console.error(e)
  }
}

const toggleFavorite = async (product) => {
  try {
    await productApi.toggleFavorite(product.id)
    product.is_favorite = product.is_favorite ? 0 : 1
    ElMessage.success(product.is_favorite ? '已收藏' : '已取消收藏')
  } catch (e) {
    console.error(e)
  }
}
</script>

<style scoped lang="scss">
.product-card {
  margin-bottom: 16px;
  
  .product-meta {
    display: flex;
    justify-content: space-between;
    align-items: center;
  }
}
</style>
